# makefile for error_estimates
#
#
include $(MAKECFG).$(SYSTEM)



INCLUDE= -I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis
SRC = error_estimates.c error_estimates.h
OBJS = error_estimates.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT=error_estimates
LINK="1"



include $(MAKELIB).$(SYSTEM)

