# makefile for bffit
#
#
include $(MAKECFG).$(SYSTEM)



INCLUDE= -I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis
SRC = bffit.c bffit.h
OBJS = bffit.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT=bffit
LINK="1"



include $(MAKELIB).$(SYSTEM)
