# makefile for lmfit
#
#
include $(MAKECFG).$(SYSTEM)



INCLUDE= -I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis
SRC = lmfit2.c lmfit2.h
OBJS = lmfit2.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT=lmfit2
LINK="1"



include $(MAKELIB).$(SYSTEM)
