# Makefile for self clutter estimation library
# ========================
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn 

SRC = selfclutter.c
OBJS = selfclutter.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = selfclutter








 

 















include $(MAKELIB).$(SYSTEM)
